### ISSUE TITLE
Testing New Futures

### ISSUE THREAD

**Issue by felipealfonsog** [felipealfonsog/TermPDFViewer#108]
I added a new future to search inside the pdf files.. Please let's try to test it.. @PardesiCat

**Comment by felipealfonsog** [comment]
After installing this new version, please close the terminal and open a new one before calling the program to avoid any issues. The paths where the binary is installed have been modified, and the system may need to update to recognize the executable's correct location

**Comment by felipealfonsog** [comment]
@PardesiCat g'day mate ! is it working on your system ? Cheers !

**Comment by PardesiCat** [comment]
## Working 

Yes, the new version is working totally fine. I can search keywords both with capital and small letters (I mean, even in pdf, the letter is in capital, but in search query, I put small letter, which it seraching words perfectly). totally fine
As you can see, it highlighted my name (red color), which I searched for.

![fine](https://github.com/felipealfonsog/TermPDFViewer/assets/55957190/0acf2c83-c592-4d35-a324-d9236bd581d6)

## Other things
But there was another thing that didn't matter, so I kept this information in case it was useful.
when using things like autofill in a Linux terminal, such as fish shell
that Python file is coming in suggestion **termpdf.py**   (maybe becoz its install inside /usr/share/bin

![finesug](https://github.com/felipealfonsog/TermPDFViewer/assets/55957190/34d8574e-c9c2-46b1-88f7-001b36dc77de)

**Comment by felipealfonsog** [comment]
Hey there! I noticed your mention of using autofill in a Linux terminal with the fish shell, but I'm not quite sure I understand what you mean by autofill. Could you please elaborate or provide more details? I'd be happy to help, but I want to make sure I grasp the concept correctly. I don't really know what you are trying to do.

**Comment by PardesiCat** [comment]
Hi   actually  when you use shells like Fish 

they have feature   like  autosuggestion  

there sometimes  **termpdf.py**   is appering  while trying to type  **term**

watch this video maybe you can understand ...   this causing no problem  but i  notice so i just informing you 

even you can try type   termpdf.py   in ur terminal (any other shells like bash or zsh)  u can see  (maybe becoz its install inside /usr/share/bin )


https://github.com/felipealfonsog/TermPDFViewer/assets/55957190/2e1da438-f05b-45ff-8801-08e3833c1c07

**Comment by felipealfonsog** [comment]
Ah, I see. However, that seems to be related to a utility or system option. I personally don't use autocomplete, and thus, I haven't encountered such issues. It might be helpful to refer to the documentation for autocomplete in your Linux shell. As I mentioned, I haven't faced such problems since I don't use autocomplete. So, it might not be an inherent issue with the program itself.. The good thing is that the program is running without any trouble once you type term-pdf in a specified folder, right?

**Comment by PardesiCat** [comment]
yess its totally working fine 


i just gave that info  ...  becoz users can see  apart from terminal   others ways that  there system have  something installed  termpdf.py     nothing else  ..... as u can see  it appers in dmenu when i search  term-     


else  whole during my test  program is working fine   :)
