### ISSUE TITLE
Testing the project / Ideas to move forward with the installer

### ISSUE THREAD

**Issue by felipealfonsog** [felipealfonsog/TermPDFViewer#56]
I'm thinking in different options to make the installer easier and faster. 
I need ideas. Let's share some feedback.

**Comment by PardesiCat** [comment]
you mean  installer script or something else?

**Comment by felipealfonsog** [comment]
Yeah .. there's something wrong during the installation ... I'm trying to figure out how to make it faster and easier and effective in AUR ... yesterday I made some changes ... could you please test it ? If you have different ideas 💡 please let me know ...

**Comment by PardesiCat** [comment]
HI i tested  these errors am getiing

## With raw pkgbuild you wrote

![raw-termpdf](https://github.com/felipealfonsog/TermPDFViewer/assets/55957190/840d8f87-892d-43cc-b2e7-edf5b02a54f3)


## with pyinstaller 

Here for test i preinstalled  [pyinstaller from aur](https://aur.archlinux.org/packages/pyinstaller)  before installing term-pdf

and this error i got 

![pyinstaller](https://github.com/felipealfonsog/TermPDFViewer/assets/55957190/7e56dab0-d3ac-4417-a39f-46d4ffad65f8)
 

> I just commented these codes before start installed in pkgbuild like this
```
# if ! command -v pyinstaller &>/dev/null; then
    #  pip install pyinstaller
  #  fi


```

**Comment by felipealfonsog** [comment]
You don't get it. I know there are errors. I need ideas as I said to make a better installer ... that's what I need. Ideas.

**Comment by PardesiCat** [comment]
and 1 think to ask   

how yo0u compiled the project in your system ? 

can u tell the process maybe that can help  to get more packing idea

**Comment by felipealfonsog** [comment]
the same way I tried to make it through AUR now ... but in AUR, is not working ... perhaps I need to go with a different approach .... I don't know, I need ideas ... lots of it ---- this project could be really interesting.. I'm always reading pdf files and to have the ability to read on the terminal would make my life really easy ... perhaps for many other people too ... so I guess it's promessing ... I just need to clear the path for a smooth installation ... .

**Comment by PardesiCat** [comment]
can u try this  type   things  with   venv enviroment 

https://git.pardesicat.xyz/opensource/blackarch-pkgbuilds/src/branch/master/PKGBUILD-python-standalone

https://git.pardesicat.xyz/opensource/blackarch-pkgbuilds/src/branch/master/python-standalone.install

**Comment by felipealfonsog** [comment]
have you done it in the past in a practical project of yours ? ...

**Comment by PardesiCat** [comment]
not mine project  but 

here once i proposed this tool to add Blackarch  

so for demo i  did with this tool   as u can see

https://git.pardesicat.xyz/pardesicat/blackarch-ddosattck-pkgbuild


+  this one  i tried with this  pkgbuild which works fine 

https://git.pardesicat.xyz/pardesicat/blackarch-objection


sometimes i do this kind of tesing stuffs  go gain experience

**Comment by felipealfonsog** [comment]
Very interesting !. Thanks. I'm thinking maybe to use a different programming language though .. idk .. I'm analysing any kind of alternatives ..

**Comment by PardesiCat** [comment]
ahhh all the best  ....

**Comment by felipealfonsog** [comment]
Are you good in programming .. software engineering..?

**Comment by PardesiCat** [comment]
no ,,, am no programmer .. infact am not a CS student  

am trying to learn cybersecurity by myself

**Comment by felipealfonsog** [comment]
I see, but I deeply respect your self-driven learning and your insatiable thirst for knowledge!- :)

**Comment by PardesiCat** [comment]
Hei thanks... for the compliment. **:)**

**Comment by felipealfonsog** [comment]
Hey there! Could you please test it? I found a way to make it work in any folder, which was my main and first idea. Actually, I created this project for my personal use, as it makes my life much easier. I prefer running terminals over other things—cleaner and uses less memory!

I know there are things I need to check afterward to ensure it's working fine and not just an experimental project. However, I believe it should work in any folder now, just to scan and read PDFs in the terminal.

Could you please test it? Clean the cache with: `yay -Scc`, and then reinstall it with: `yay -S term-notes`.

I hope it's working on your machine. I tested it on mine, and it's working well.

Thanks!

**Comment by PardesiCat** [comment]
Hi  install was successfull

but when i run its showing this

![term-pdf](https://github.com/felipealfonsog/TermPDFViewer/assets/55957190/34b64ec6-0719-4697-9641-da36fb29284d)

**Comment by felipealfonsog** [comment]
> Hi  install was successfull
> 
> 
> 
> but when i run its showing this
> 
> 
> 
> ![term-pdf](https://github.com/felipealfonsog/TermPDFViewer/assets/55957190/34b64ec6-0719-4697-9641-da36fb29284d)
> 
> 
> 
> 

Very strange on my machine I have no errors. 
Reading the prompt it could be an memory related issue .. I'll review the code now, debug it, and update the code in two important files that are executed. 
I'm a few minutes I'll let you know. 

Thanks ! 

PD.: it's not necessary a screenshot next time .. just pasting the output or the error here it's much better ... so I can copy easily and dive into errors. 

Thanks !

**Comment by felipealfonsog** [comment]
Alright ! @PardesiCat  I changed a few things in the code, some other things related with the logic... (this is experimental.. right now the most important thing it's to make it work and find a practical logical path... for me, and the project.) And, It's working now, in two machines with Arch ... and even in MacOS with the bash installer .... 
Please could you please check it and test it on your system ? 
Remember,  Clean the cache with: yay -Scc, and then reinstall it with: yay -S term-pdf ! :) right now the latest version is 0.0.3.9 ! :) 
Thanks a lot!
Cheers!

**Comment by felipealfonsog** [comment]
If it's working, to celebrate, you can share a delightful screenshot with the program running and showcasing your desktop. I love to see how Linux desktops are set up though ! 😊

**Comment by PardesiCat** [comment]
HI   i was  already testing   the .0.0.3.8

there some thing 2nd line  install dm750    (not working 
and new  

i just notice u updated it before i comment 

and new hash 

sha256sums=('ff15c7a79a4b13eb067e28408e18c7333b609b7d76f2bb3039072df9125688ab')


there 1thing i recommonded while i tested  

add   gcc  now in depends

and chmod +x  after install

here i putted  the  working  PKGBUILD 

and now everything working fine

![workign](https://github.com/felipealfonsog/TermPDFViewer/assets/55957190/4e076565-4c31-40df-857a-f44f5604bdd2)


im putting the pkbuild i changed

## PKGBUILD

```
# Mantenedor: Felipe Alfonso Gonzalez <f.alfonso@res-ear.ch>
pkgname=term-pdf
pkgver=0.0.3.8
pkgrel=1
pkgdesc="TermPDF Viewer is an open-source PDF file viewer designed to run in the terminal."
arch=('x86_64')
url="https://github.com/felipealfonsog/TermPDFViewer"
license=('MIT')
depends=('python-pip' 'python-pymupdf' 'gcc' )
source=("https://github.com/felipealfonsog/TermPDFViewer/archive/refs/tags/v.${pkgver}.tar.gz")
sha256sums=('ff15c7a79a4b13eb067e28408e18c7333b609b7d76f2bb3039072df9125688ab')

prepare() {
  tar xf "v.${pkgver}.tar.gz" -C "$srcdir" --strip-components=1
  # cp "$srcdir"/term-pdf-wrp.c "$srcdir"/TermPDFViewer-v."$pkgver"/src/
}
build() {
  cd "$srcdir"/TermPDFViewer-v."${pkgver}"
  gcc -o term-pdf-wrp "$srcdir"/TermPDFViewer-v."${pkgver}"/src/term-pdf-wrp.c
}
package() {
  install -Dm755 "$srcdir"/TermPDFViewer-v."${pkgver}"/src/term-pdf-wrp "${pkgdir}/usr/bin/term-pdf"
   chmod +x /usr/bin/term-pdf

  install -Dm755 "$srcdir"/TermPDFViewer-v."${pkgver}"/src/termpdf.py "${pkgdir}/$HOME/.config/termpdf.py"
}
```

**Comment by felipealfonsog** [comment]
I've made extensive changes from version 0.0.3.8, and the PKGBUILD used for it is no longer applicable. The current version is 0.0.3.9, and I'd appreciate it if you could test the installation to ensure everything is functioning smoothly.

Please confirm that the installation of version 0.0.3.9 is successful. At this stage, my primary focus is on achieving functionality without any warnings or errors. I'm working on establishing a solid logic for the program, and secondary aspects will be reviewed once full functionality is achieved.

Kindly please! share a screenshot of version 0.0.3.9 after installation and running! Your feedback is greatly appreciated. :) 

Thanks a bunch!

**Comment by PardesiCat** [comment]
## v 0.0.3.9   working fine and it can detect  pdf files

yess now  everything fine 

![tp-9](https://github.com/felipealfonsog/TermPDFViewer/assets/55957190/fe7e2877-6d35-4419-945e-03dcc420a69c)


yess when i typing the issue you already uploaded 0.0.3.9
and working fine

**Comment by felipealfonsog** [comment]
Yeah great thanks! It's also working on macOS! ..

![Screen Shot 2023-10-17 at 04 18 59](https://github.com/felipealfonsog/TermPDFViewer/assets/7793517/b1dcafa6-d951-4efb-886d-0ed871f197e5)
![Screen Shot 2023-10-17 at 04 19 15](https://github.com/felipealfonsog/TermPDFViewer/assets/7793517/34545e2b-62ef-4200-badb-2cee52cc50af)

**Comment by PardesiCat** [comment]
Yes, the project idea was cool. View the PDF inside Terminal.

I am glad and happy to be part of your project.

I have some suggestions to give. I will put them in more detail later.




and here is the compiled arch package I im putting here in case you need to inspect.

https://mirror.pardesicat.xyz/pardesicat-repository/pardesicat-repository/x86_64/term-pdf-0.0.3.9-1-x86_64.pkg.tar.zst

working totally

**Comment by felipealfonsog** [comment]
Awesome! Thanks!
